In [37]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

In [38]:
df = pd.read_csv("iris.csv")

In [39]:
df[:10]

sepalLength  sepalWidth  petalLength  petalWidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa
5          5.4         3.9          1.7         0.4  Iris-setosa
6          4.6         3.4          1.4         0.3  Iris-setosa
7          5.0         3.4          1.5         0.2  Iris-setosa
8          4.4         2.9          1.4         0.2  Iris-setosa
9          4.9         3.1          1.5         0.1  Iris-setosa

In [40]:
datos= df.values[:,:4]
etiquetas= df.values[:,4]

In [41]:
encoder = LabelEncoder()
encoder.fit(etiquetas)
encoded_Y = encoder.transform(etiquetas)
etiquetas_ = np_utils.to_categorical(encoded_Y)

In [42]:
X_train, X_test, y_train, y_test = train_test_split(datos, etiquetas_, test_size=0.2, random_state=42)

In [43]:
model = Sequential()
model.add(Dense(16, input_dim=4, activation='relu'))
model.add(Dense(3, activation='sigmoid'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [44]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 16)                80        
_________________________________________________________________
dense_4 (Dense)              (None, 3)                 51        
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [45]:
model.fit(X_train, y_train, epochs=150, batch_size=5)

Epoch 1/150
120/120 [==============================] - 0s 2ms/step - loss: 1.0425 - acc: 0.1417
Epoch 2/150
120/120 [==============================] - 0s 433us/step - loss: 0.9905 - acc: 0.2167
Epoch 3/150
120/120 [==============================] - 0s 400us/step - loss: 0.9516 - acc: 0.3167
Epoch 4/150
120/120 [==============================] - 0s 416us/step - loss: 0.9228 - acc: 0.3250
Epoch 5/150
120/120 [==============================] - 0s 441us/step - loss: 0.8968 - acc: 0.3250
Epoch 6/150
120/120 [==============================] - 0s 458us/step - loss: 0.8696 - acc: 0.4583
Epoch 7/150
120/120 [==============================] - 0s 458us/step - loss: 0.8446 - acc: 0.6500
Epoch 8/150
120/120 [==============================] - 0s 425us/step - loss: 0.8161 - acc: 0.6583
Epoch 9/150
120/120 [==============================] - 0s 433us/step - loss: 0.7862 - acc: 0.6583
Epoch 10/150
120/120 [==============================] - 0s 566us/step - loss: 0.7626 - acc: 0.6833
Epoch 11/150
120/120 

120/120 [==============================] - 0s 366us/step - loss: 0.1953 - acc: 0.9750
Epoch 83/150
120/120 [==============================] - 0s 416us/step - loss: 0.1940 - acc: 0.9667
Epoch 84/150
120/120 [==============================] - 0s 533us/step - loss: 0.1928 - acc: 0.9667
Epoch 85/150
120/120 [==============================] - 0s 525us/step - loss: 0.1879 - acc: 0.9750
Epoch 86/150
120/120 [==============================] - 0s 410us/step - loss: 0.1859 - acc: 0.9750
Epoch 87/150
120/120 [==============================] - 0s 415us/step - loss: 0.1885 - acc: 0.9583
Epoch 88/150
120/120 [==============================] - 0s 375us/step - loss: 0.1847 - acc: 0.9833
Epoch 89/150
120/120 [==============================] - 0s 408us/step - loss: 0.1852 - acc: 0.9667
Epoch 90/150
120/120 [==============================] - 0s 375us/step - loss: 0.1859 - acc: 0.9667
Epoch 91/150
120/120 [==============================] - 0s 416us/step - loss: 0.1810 - acc: 0.9667
Epoch 92/150
120/120 [=

In [46]:
scores = model.evaluate(X_test, y_test)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

30/30 [==============================] - 0s 2ms/step

acc: 96.67%


In [72]:
n_layer = 0
B_Input_Hidden = model.layers[n_layer].get_weights()
print("Dimensiones de los pesos de la capa {}: \n {} \n".format(n_layer,B_Input_Hidden[0]))
print("Dimensiones del Bias de la capa {}: \n {} ".format(n_layer,B_Input_Hidden[1]))

Dimensiones de los pesos de la capa 0: 
 [[ 0.6879192   1.027729    0.23832688  0.28149384 -0.24097238 -0.32083574
   0.09654245 -0.24681091 -0.38728964  0.28540212 -0.2895755  -0.12873107
  -0.27290514  0.47960132 -0.16924262  0.18743744]
 [-0.08452196  0.7748494  -0.7971831  -0.45667416 -0.27307832 -0.30360162
   0.0087458  -0.12751636  0.25607675 -0.45289114  0.38897616 -0.4786837
   0.2862532   1.0586693  -0.3017729  -0.58322597]
 [ 0.6348956  -0.63204485  0.04571527 -0.49880263  0.8026024   0.03566074
  -0.36305746  0.01405573  0.05625397  0.16342498 -0.1546501   0.03476465
  -0.19107747 -0.03845914 -0.17534158  0.66913533]
 [ 0.29454336 -1.1381596   0.98611087  0.39851242  0.8310197  -0.1791
  -0.45925748  0.2927724  -0.44956458 -0.12593642  0.35841343 -0.30742925
  -0.53649884 -0.27094552 -0.17885816  0.6757126 ]] 

Dimensiones del Bias de la capa 0: 
 [ 0.42305782  0.8673452  -0.47923553  0.         -0.38130704  0.
 -0.06785009  0.          0.          0.04286429 -0.01093684  0

In [73]:
n_layer = 1
B_Input_Hidden =  model.layers[n_layer].get_weights()
print("Dimensiones de los pesos de la capa {}: \n {} \n".format(n_layer,B_Input_Hidden[0]))
print("Dimensiones del Bias de la capa {}: \n{} ".format(n_layer,B_Input_Hidden[1]))

Dimensiones de los pesos de la capa 1: 
 [[-0.9285466  -0.00947846 -0.42134324]
 [ 0.57885015  0.02108198 -1.0007355 ]
 [-0.4177649  -0.9973735   1.2575829 ]
 [-0.02497649  0.18526626  0.1308018 ]
 [-1.3341012  -0.53920025  0.9432397 ]
 [ 0.23410201 -0.2848405  -0.401398  ]
 [-0.49265578  0.03694439 -0.02681982]
 [-0.48015767 -0.01647884  0.08020812]
 [-0.4810232   0.23577195  0.4187513 ]
 [-0.85200304  0.33393592 -0.01484706]
 [-0.35719448 -0.15947568 -0.08850373]
 [-0.11973548 -0.02175778  0.3005815 ]
 [ 0.525533    0.46670657 -0.4073873 ]
 [ 0.18887398 -0.76088506 -0.6123799 ]
 [-0.18257904 -0.5143805   0.03696311]
 [-1.977876   -0.34474075  0.49153057]] 

Dimensiones del Bias de la capa 1: 
[ 0.09769254 -0.01791726 -0.67817557] 


In [49]:
a =  model.layers[0].get_weights()

In [50]:
for u in range(0, 4):
    #for i in range(0, 15):
    print(a[0][u])

[ 0.6879192   1.027729    0.23832688  0.28149384 -0.24097238 -0.32083574
  0.09654245 -0.24681091 -0.38728964  0.28540212 -0.2895755  -0.12873107
 -0.27290514  0.47960132 -0.16924262  0.18743744]
[-0.08452196  0.7748494  -0.7971831  -0.45667416 -0.27307832 -0.30360162
  0.0087458  -0.12751636  0.25607675 -0.45289114  0.38897616 -0.4786837
  0.2862532   1.0586693  -0.3017729  -0.58322597]
[ 0.6348956  -0.63204485  0.04571527 -0.49880263  0.8026024   0.03566074
 -0.36305746  0.01405573  0.05625397  0.16342498 -0.1546501   0.03476465
 -0.19107747 -0.03845914 -0.17534158  0.66913533]
[ 0.29454336 -1.1381596   0.98611087  0.39851242  0.8310197  -0.1791
 -0.45925748  0.2927724  -0.44956458 -0.12593642  0.35841343 -0.30742925
 -0.53649884 -0.27094552 -0.17885816  0.6757126 ]


In [51]:
b =  model.layers[1].get_weights()

In [52]:
for i in range(0, 16):
    print(b[0][i])

[-0.9285466  -0.00947846 -0.42134324]
[ 0.57885015  0.02108198 -1.0007355 ]
[-0.4177649 -0.9973735  1.2575829]
[-0.02497649  0.18526626  0.1308018 ]
[-1.3341012  -0.53920025  0.9432397 ]
[ 0.23410201 -0.2848405  -0.401398  ]
[-0.49265578  0.03694439 -0.02681982]
[-0.48015767 -0.01647884  0.08020812]
[-0.4810232   0.23577195  0.4187513 ]
[-0.85200304  0.33393592 -0.01484706]
[-0.35719448 -0.15947568 -0.08850373]
[-0.11973548 -0.02175778  0.3005815 ]
[ 0.525533    0.46670657 -0.4073873 ]
[ 0.18887398 -0.76088506 -0.6123799 ]
[-0.18257904 -0.5143805   0.03696311]
[-1.977876   -0.34474075  0.49153057]


In [53]:
X_test[13]

array([4.9, 3.1, 1.5, 0.1], dtype=object)

In [54]:
y_test[13]

array([1., 0., 0.], dtype=float32)

In [55]:
X_test

array([[6.1, 2.8, 4.7, 1.2],
       [5.7, 3.8, 1.7, 0.3],
       [7.7, 2.6, 6.9, 2.3],
       [6.0, 2.9, 4.5, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [5.4, 3.4, 1.5, 0.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.9, 3.1, 5.1, 2.3],
       [6.2, 2.2, 4.5, 1.5],
       [5.8, 2.7, 3.9, 1.2],
       [6.5, 3.2, 5.1, 2.0],
       [4.8, 3.0, 1.4, 0.1],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.1, 3.8, 1.5, 0.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.5, 3.0, 5.8, 2.2],
       [5.6, 2.5, 3.9, 1.1],
       [5.7, 2.8, 4.5, 1.3],
       [6.4, 2.8, 5.6, 2.2],
       [4.7, 3.2, 1.6, 0.2],
       [6.1, 3.0, 4.9, 1.8],
       [5.0, 3.4, 1.6, 0.4],
       [6.4, 2.8, 5.6, 2.1],
       [7.9, 3.8, 6.4, 2.0],
       [6.7, 3.0, 5.2, 2.3],
       [6.7, 2.5, 5.8, 1.8],
       [6.8, 3.2, 5.9, 2.3],
       [4.8, 3.0, 1.4, 0.3],
       [4.8, 3.1, 1.6, 0.2]], dtype=object)

In [56]:
y_test

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [63]:
print(np.array([X_test[0]]))

[[6.1 2.8 4.7 1.2]]


In [64]:
predictions = model.predict(X_test)

In [65]:
predictions

array([[1.4570844e-06, 1.7659620e-03, 1.8663656e-04],
       [7.6783055e-01, 6.2300544e-03, 2.1622650e-07],
       [3.3424522e-12, 3.8725717e-05, 4.4549957e-02],
       [1.3369430e-06, 1.3537904e-03, 3.4277872e-04],
       [3.8158436e-07, 9.0561307e-04, 1.5976440e-04],
       [6.8588024e-01, 9.4965296e-03, 6.6182321e-07],
       [7.6295837e-05, 3.8450910e-03, 7.7180397e-05],
       [1.0852472e-08, 1.9246152e-04, 2.1903629e-03],
       [1.5672400e-07, 1.0780724e-03, 1.9878547e-03],
       [2.0001122e-05, 3.2886674e-03, 1.1374019e-04],
       [5.1359780e-08, 3.6834128e-04, 1.0115491e-03],
       [7.2878158e-01, 1.5700946e-02, 1.9658992e-06],
       [8.0688912e-01, 8.3354432e-03, 3.4421893e-07],
       [7.2509927e-01, 1.4047423e-02, 1.5140635e-06],
       [8.2074207e-01, 7.1942243e-03, 5.2775823e-07],
       [1.3443713e-06, 9.7541272e-04, 1.3299398e-04],
       [1.1489018e-09, 1.6597389e-04, 1.0653295e-02],
       [1.7208909e-05, 4.0032468e-03, 1.9170129e-04],
       [2.3262305e-06, 2.044

In [66]:
valmult = 10
print("|----------------------------------------------------------|")
print("|         Welcome to Iris Neural Network, by Sandro        |")
print("|        Labels prediction accuaracy TensorFlow(100%)      |")
print("|----------------------------------------------------------|")
print("|      features       |   real labels   |  predic labels   |")
print("|---------------------|-----------------|------------------|")
for i in range(0,30):
    print( "| {}  {}  {}  {}  |  {}  {}  {}  | {:3.2f}  {:3.2f}  {:3.2f} |" .
          format(X_test[i][0], X_test[i][1],X_test[i][2],X_test[i][3], y_test[i][0], y_test[i][1],y_test[i][2],
                 valmult*predictions[i][0], valmult*predictions[i][1], valmult*predictions[i][2]) ) 
    
print("|----------------------------------------------------------|")

|----------------------------------------------------------|
|         Welcome to Iris Neural Network, by Sandro        |
|        Labels prediction accuaracy TensorFlow(100%)      |
|----------------------------------------------------------|
|      features       |   real labels   |  predic labels   |
|---------------------|-----------------|------------------|
| 6.1  2.8  4.7  1.2  |  0.0  1.0  0.0  | 0.00  0.02  0.00 |
| 5.7  3.8  1.7  0.3  |  1.0  0.0  0.0  | 7.68  0.06  0.00 |
| 7.7  2.6  6.9  2.3  |  0.0  0.0  1.0  | 0.00  0.00  0.45 |
| 6.0  2.9  4.5  1.5  |  0.0  1.0  0.0  | 0.00  0.01  0.00 |
| 6.8  2.8  4.8  1.4  |  0.0  1.0  0.0  | 0.00  0.01  0.00 |
| 5.4  3.4  1.5  0.4  |  1.0  0.0  0.0  | 6.86  0.09  0.00 |
| 5.6  2.9  3.6  1.3  |  0.0  1.0  0.0  | 0.00  0.04  0.00 |
| 6.9  3.1  5.1  2.3  |  0.0  0.0  1.0  | 0.00  0.00  0.02 |
| 6.2  2.2  4.5  1.5  |  0.0  1.0  0.0  | 0.00  0.01  0.02 |
| 5.8  2.7  3.9  1.2  |  0.0  1.0  0.0  | 0.00  0.03  0.00 |
| 6.5  3.2  5.1  2.0  | 